version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python clean_db.py
    command: python app.py
    dns:
      - 8.8.8.8
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    depends_on:
      - db

  db:
    image: "mongo:6.0.3"
    ports:
      - "27017:27017"
    environment:
      - DB_ROOT_PASSWORD=password
      - DB_ROOT_HOST="127.0.0.1"
    volumes:
      - "./db:/app/db"